apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
  namespace: togglemaster
type: Opaque
stringData:
  POSTGRES_HOST: togglemaster-auth-db.c3bbpkj3pcmk.us-east-1.rds.amazonaws.com
  POSTGRES_DB: auth_db
  POSTGRES_USER: tm_user
  POSTGRES_PASSWORD: tm_pass_26
